# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 12:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('educases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('subcategory_exists', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Economy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('subcategory_exists', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Science',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('subcategory_exists', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='subcategory_exists',
        ),
        migrations.AddField(
            model_name='science',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educases.Subject'),
        ),
        migrations.AddField(
            model_name='economy',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educases.Subject'),
        ),
        migrations.AddField(
            model_name='art',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educases.Subject'),
        ),
    ]
